#pragma once

#define WAVEX_FRONTEND_VERSION_MAJOR 0
#define WAVEX_FRONTEND_VERSION_MINOR 1
#define WAVEX_FRONTEND_VERSION_PATCH 0
#define WAVEX_FRONTEND_VERSION_BUILD "dev"

#define WAVEX_BACKEND_VERSION_MAJOR 0
#define WAVEX_BACKEND_VERSION_MINOR 1  
#define WAVEX_BACKEND_VERSION_PATCH 0
#define WAVEX_BACKEND_VERSION_BUILD "dev"

// Generate version strings
#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define WAVEX_FRONTEND_VERSION_STRING \
    TOSTRING(WAVEX_FRONTEND_VERSION_MAJOR) "." \
    TOSTRING(WAVEX_FRONTEND_VERSION_MINOR) "." \
    TOSTRING(WAVEX_FRONTEND_VERSION_PATCH) "-" \
    WAVEX_FRONTEND_VERSION_BUILD

#define WAVEX_BACKEND_VERSION_STRING \
    TOSTRING(WAVEX_BACKEND_VERSION_MAJOR) "." \
    TOSTRING(WAVEX_BACKEND_VERSION_MINOR) "." \
    TOSTRING(WAVEX_BACKEND_VERSION_PATCH) "-" \
    WAVEX_BACKEND_VERSION_BUILD

// Compile-time information
#define WAVEX_COMPILE_DATE __DATE__
#define WAVEX_COMPILE_TIME __TIME__

// Project information
#define WAVEX_PROJECT_NAME "WaveX"
#define WAVEX_PROJECT_DESCRIPTION "Dual-MCU Sampler/Synthesizer" 